version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: rag_postgres
    environment:
      POSTGRES_USER: rag_user
      POSTGRES_PASSWORD: rag_pass
      POSTGRES_DB: rag_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rag_network

volumes:
  postgres_data:

networks:
  rag_network:
    driver: bridge
